server:
  servlet:
    context-path: /sample-web
  port: 7081
spring:
  datasource:
    url: jdbc:h2:file:/Users/somnath.pal1/mywork/db/data/country
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  security:
    user:
      name: admin
      password: admin
  application:
    name: spring-web-security

logging:
  level:
    org.springframework.security: DEBUG


